Deply new change

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -61,52 +61,33 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1
       run: |
-        FUNCTION_NAME="cicd_lambda_${{ github.ref_name }}"
+        FUNCTION_NAME="cicd_lambda_${GITHUB_REF_NAME}"
         REGION="us-east-1"
-        echo "Deploying to Lambda function: $FUNCTION_NAME"
 
-        # Check if the Lambda function exists
+        echo "Deploying Lambda: $FUNCTION_NAME"
+        ls -la lambda_function
+        test -f lambda_function/lambda.zip || { echo "lambda.zip not found"; exit 1; }
+
         FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region $REGION || echo "false")
 
-        ENV_VARS="Variables={ENV=${{ env.ENV }},API_KEY=${{ env.API_KEY }},LOG_LEVEL=${{ env.LOG_LEVEL }}}"
+        ENV_VARS="Variables={ENV=${ENV},API_KEY=${API_KEY},LOG_LEVEL=${LOG_LEVEL}}"
 
         if [ "$FUNCTION_EXISTS" == "false" ]; then
-          echo "Creating Lambda function $FUNCTION_NAME..."
+          echo "Creating Lambda..."
           aws lambda create-function \
             --function-name $FUNCTION_NAME \
             --runtime python3.11 \
             --role arn:aws:iam::731439570860:role/test_dev \
             --handler app.lambda_handler \
             --timeout 300 \
-            --zip-file fileb://lambda.zip \
+            --zip-file fileb://lambda_function/lambda.zip \
             --region $REGION \
             --environment "$ENV_VARS"
         else
-          echo "Updating Lambda function $FUNCTION_NAME..."
+          echo "Updating Lambda..."
           aws lambda update-function-code \
             --function-name $FUNCTION_NAME \
             --region $REGION \
-            --zip-file fileb://lambda.zip
-
-          # Wait for function code update to complete
-          echo "Waiting for function code update to complete..."
-          while true; do
-            UPDATE_STATUS=$(aws lambda get-function --function-name $FUNCTION_NAME --region $REGION --query 'Configuration.LastUpdateStatus' --output text)
-            if [ "$UPDATE_STATUS" == "Successful" ]; then
-              echo "Function code update completed successfully."
-              break
-            elif [ "$UPDATE_STATUS" == "Failed" ]; then
-              echo "Function code update failed."
-              exit 1
-            else
-              echo "Update in progress, waiting..."
-              sleep 5
-            fi
-          done
-
-          # Update function configuration
-          aws lambda update-function-configuration \
-            --function-name $FUNCTION_NAME \
-            --region $REGION \
-            --environment "$ENV_VARS"
+            --zip-file fileb://lambda_function/lambda.zip
         fi
+
